### ISSUE TITLE
Improve organisation of Coq code!

### ISSUE THREAD

**Issue by MatthewDaggitt** [Timothy-G-Griffin/CAS#3]
Maybe (?):

- Sort everything in `theory` by prefix (e.g. `bop`, `bops`, `brel` etc.) into folders
- Move the top-level folders `a_code`, `code`, `extract`, `theory`, `verify` into `src`
- Go through removing all the temporary emacs files that have snuck in (all files matching *.*~). Already been added to the `.gitignore` file

**Comment by Timothy-G-Griffin** [comment]
The first and third points are done.  I don't agree with 
point 2 --- /src is for the ocaml-only code.  Perhaps /extraction should 
be a subdirectory.  See new Issue on splitting project into two.
